# Generated by Django 2.0.5 on 2018-05-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('s', 'super'), ('l', 'leader'), ('m', 'member')], default='s', max_length=1),
            preserve_default=False,
        ),
    ]
