# Generated by Django 2.0.5 on 2018-06-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_userentityrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='userentityrelation',
            name='relation_type',
            field=models.CharField(choices=[('l', 'leader'), ('m', 'member')], default='m', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email',)},
        ),
    ]
