# Generated by Django 2.0.5 on 2018-06-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='members',
        ),
    ]
