# Generated by Django 2.0.5 on 2018-06-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20180608_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='desciption',
            new_name='description',
        ),
    ]
