# Generated by Django 2.0.5 on 2018-06-28 16:20

from django.db import migrations, models
import random
randlist = ['Hi', 'Bye', 'A', 'B', 'C']

class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20180625_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='slug',
            field=models.SlugField(default=random.randint(1,1000), max_length=100),
            preserve_default=False,
        ),
    ]
