# Generated by Django 2.0.5 on 2018-06-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_entity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
