# Generated by Django 2.0.5 on 2018-06-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='expiration_time',
            field=models.DateTimeField(default='2018-01-01'),
            preserve_default=False,
        ),
    ]
