# Generated by Django 2.0.5 on 2018-06-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='hours_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
